### ISSUE TITLE
ionic1

### ISSUE THREAD

**Issue by gbelmm** [mgnstudio7/stenciljs-virtual-scroll#1]
good job, is an example with ionic1 possible?

**Comment by mgnstudio7** [comment]
thx, i.m not tested on v1, but web components can use in any frameworks, because is just javascript.
If you will test on v1, please inform me.

**Comment by gbelmm** [comment]
can you post it in npm?

https://stenciljs.com/docs/distribution

**Comment by mgnstudio7** [comment]
it is posted in npm
`npm install stenciljs-virtual-scroll --save`
