### ISSUE TITLE
Step 4. Copying the Components

### ISSUE THREAD

**Issue by pcsantana** [mgnstudio7/stenciljs-virtual-scroll#2]
Hi, thank you for this component!
I'm trying to use it, but I don't know how can I modify the collection in the assets array of the .angular-cli.json file. Actually, I could't find the file in my Ionic project.

Could you help me with this?
Thank you!

**Comment by mgnstudio7** [comment]
@pcsantana, your ionic version?

**Comment by pcsantana** [comment]
The last one, 3.9.2.
My structure project is similar to the [Ionic App Conference](https://github.com/ionic-team/ionic-conference-app).

**Comment by mgnstudio7** [comment]
after npm install package, you must use app-script to copy web component files in www directory

1. Add in package.json 
```json
"config": {
    "ionic_copy": "./config/copy.config.js"
  }
```

2. Create config/copy.config.js and put in

```ts
// this is a custom dictionary to make it easy to extend/override
// provide a name for an entry, it can be anything such as 'copyAssets' or 'copyFonts'
// then provide an object with a `src` array of globs and a `dest` string
module.exports = {
    copyAssets: {
      src: ['{{SRC}}/assets/**/*'],
      dest: '{{WWW}}/assets'
    },
    copyIndexContent: {
      src: ['{{SRC}}/index.html', '{{SRC}}/manifest.json', '{{SRC}}/service-worker.js'],
      dest: '{{WWW}}'
    },
    copyFonts: {
      src: ['{{ROOT}}/node_modules/ionicons/dist/fonts/**/*', '{{ROOT}}/node_modules/ionic-angular/fonts/**/*'],
      dest: '{{WWW}}/assets/fonts'
    },
    copyPolyfills: {
      src: [`{{ROOT}}/node_modules/ionic-angular/polyfills/${process.env.IONIC_POLYFILL_FILE_NAME}`],
      dest: '{{BUILD}}'
    },
    copySwToolbox: {
      src: ['{{ROOT}}/node_modules/sw-toolbox/sw-toolbox.js'],
      dest: '{{BUILD}}'
    },
    copyVirtualScrollCore: {
      src: ['{{ROOT}}/node_modules/stenciljs-virtual-scroll/dist/stenciljs-virtual-scroll/**/*'],
      dest: '{{BUILD}}/stenciljs-virtual-scroll'
    },
    copyVirtualScroll: {
      src: ['{{ROOT}}/node_modules/stenciljs-virtual-scroll/dist/stenciljs-virtual-scroll.js'],
      dest: '{{BUILD}}'
    }
  }
```

before copyVirtualScrollCore property set standart app-script copy.config properties (if you are modify self config or my version is outdated, get only last 2 properties and put in your)

3.  And register component in app 

```html
  <script src="./build/stenciljs-virtual-scroll.js"></script>
```

4. restart app-script

**Comment by pcsantana** [comment]
Thanks for the help!
Now I'm trying to import it to use.

I'm getting the following errors:

```
 Error: Template parse errors:
'virtual-scroll' is not a known element:
1. If 'virtual-scroll' is an Angular component, then verify that it is part of this module.
2. If 'virtual-scroll' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
The steps 2 and 3 is enough?
I'm using the Ionic 3 lazyloading, and each page has your own module.
I did the steps 2 and 3 in both, app module and page module.
What else I'm doing wrong?

I appreciate if possible, some ionic demo project.
Thank you very much!

**Comment by mgnstudio7** [comment]
@pcsantana , [https://github.com/mgnstudio7/ionic-virtual-scroll-example](url)
