### ISSUE TITLE
Ionic example only working in browser

### ISSUE THREAD

**Issue by sliteleemadd** [mgnstudio7/stenciljs-virtual-scroll#3]
I have implemented the ionic 3 example which works in the browser 'ionic serve'  but nothing shows in the about tab when running on Cordova.  If you can resolve this that would be amazing! The current virtual scroll in the ionic framework is essentially broken on the more recent iOS sdks.

**Comment by mgnstudio7** [comment]
@sliteleemadd, show your "ionic info" pls.

**Comment by sliteleemadd** [comment]
'@'ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : Windows 10

**Comment by mgnstudio7** [comment]
@sliteleemadd, example project was changed. pls clone it again and test on device.

**Comment by sliteleemadd** [comment]
Still the same result. 

I cloned fresh the project at https://github.com/mgnstudio7/ionic-virtual-scroll-example ran npm i,  then >  npm i cordova, then > ionic cordova platform add android  then > ionic serve (just to see the new goods in the browser which worked just fine) and then ran > ionic cordova run android  ... launched on an Nexus 5X  running Oreo.  The app launches but when I go to the about us tab it displays no content....  Thanks for the fast response time on this issue btw.  Could this be related hash routing in stencil? I know that was also stenciljs / cordova issue.  Just taking a wild stab in the dark.  :|

**Comment by WolfWalter** [comment]
Same for me. In the console I got the error
> Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

when opening the about page.

**Comment by bmacintyre** [comment]
Any insight or intent to fix this issue?

**Comment by mgnstudio7** [comment]
@sliteleemadd 
Sorry for the long answer.
I updated the example project, change test api and tested in the browser and IPhone 5s, 6 (IOS9, 10). Works perfectly!

Please try to clone the example project again and check on your android device.
Thank you for using!

**Comment by mgnstudio7** [comment]
@WolfWalter maybe your error was related with fail api response. i change api, please test again.

**Comment by mgnstudio7** [comment]
@WolfWalter please show your 'ionic info' global packages.

**Comment by WolfWalter** [comment]
I tried again. In the browser it breaks if I scroll to the bottom of the about page and then switch to the home page and back.
With `ionic cordova run android` about is just a blank page with the mentioned error message.
ionic info:
```
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/wlt/Android/Sdk

Misc:

    backend : legacy
```

**Comment by bmacintyre** [comment]
Confirming WolfWalter findings. It now works on both Android and iOS however once I have reached the bottom and the list loads more and after leaving the about page and then returning to the about page. Scroll produces flickering of the entire list. Sometimes it should other times it disappears. But at least it displays now on the device.

**Comment by faraazc** [comment]
@mgnstudio7 @bmacintyre facing the same issue. once the list reaches the bottom and when new items are added to list and moving from about to other page and coming back about makes the scroll broken and I see empty/blank screen, items disappear and they appear back when scrolled up and down. @mgnstudio7 can you confirm this?. How to fix this any quick hack?. It's a much-needed component thanks for developing it.

**Comment by mgnstudio7** [comment]
@faraazc @bmacintyre , thx for using. I'll try to reproduce and fix this bug. I will inform you about the results.

**Comment by mgnstudio7** [comment]
@faraazc, @bmacintyre please clone example project again. If the problem persists, notify me!
